**Importing libraries**

In [ ]:
import numpy as np
import pandas as pd
import os

**Reading datasets from google drive**

Shared drive link: https://drive.google.com/drive/folders/1P396v2CjxNOZbUV69mpZIgLM-qzz59Dn?usp=sharing

Click add shortcut to drive

Note that files are not shared in Github since the new created dataset is larger than 25MB.

In [17]:
from google.colab import drive
drive.mount('/content/drive')
os.chdir('/content/drive/MyDrive/AIM tech')

Mounted at /content/drive

# Reading original dataset and adding the text to it then saving the new dataset

In [18]:
df = pd.read_csv('dialect_dataset.csv')
df

                         id dialect
0       1175358310087892992      IQ
1       1175416117793349632      IQ
2       1175450108898565888      IQ
3       1175471073770573824      IQ
4       1175496913145217024      IQ
...                     ...     ...
458192  1019484980282580992      BH
458193  1021083283709407232      BH
458194  1017477537889431552      BH
458195  1022430374696239232      BH
458196  1022409931029458944      BH

[458197 rows x 2 columns]

POST request

In [19]:
import requests

url = 'https://recruitment.aimtechnologies.co/ai-tasks'

text = list()
for i in range(0,len(df),1000):
  json_data = list(map(str,df[df.columns[0]].tolist()[i:i+1000]))
  r = requests.post(url, json=json_data)
  text.append(list(r.json().values()))

In [20]:
#To make the list of equal sized arrays: we add none at the end (in order to reshape)
text[-1] = text[-1] + [None]*803
text_arr = np.array(text).reshape(459000)
text_arr = np.delete(text_arr, np.s_[-803:])

In [21]:
#Adding fetched text to the dataset
df['text'] = text_arr

#drop id  column
df = df.drop('id', axis = 1)
df

       dialect                                               text
0           IQ   @Nw8ieJUwaCAAreT لكن بالنهاية .. ينتفض .. يغير .
1           IQ  @7zNqXP0yrODdRjK يعني هذا محسوب على البشر .. ح...
2           IQ                    @KanaanRema مبين من كلامه خليجي
3           IQ         @HAIDER76128900 يسلملي مرورك وروحك الحلوه💐
4           IQ                 @hmo2406 وين هل الغيبه  اخ محمد 🌸🌺
...        ...                                                ...
458192      BH              @Al_mhbaa_7 مبسوطين منك اللي باسطانا😅
458193      BH       @Zzainabali @P_ameerah والله ماينده ابش يختي
458194      BH  @Al_mhbaa_7 شو عملنا لك حنا تهربي مننا احنا مس...
458195      BH        @haneenalmwla الله يبارك فيها وبالعافيه 😋😋😋
458196      BH          @jolnar121 السحله ضيفي ي بتطلع لك سحليه😅😅

[458197 rows x 2 columns]

Save Dataframe

In [22]:
df.to_csv('new_dataset.csv')
df

       dialect                                               text
0           IQ   @Nw8ieJUwaCAAreT لكن بالنهاية .. ينتفض .. يغير .
1           IQ  @7zNqXP0yrODdRjK يعني هذا محسوب على البشر .. ح...
2           IQ                    @KanaanRema مبين من كلامه خليجي
3           IQ         @HAIDER76128900 يسلملي مرورك وروحك الحلوه💐
4           IQ                 @hmo2406 وين هل الغيبه  اخ محمد 🌸🌺
...        ...                                                ...
458192      BH              @Al_mhbaa_7 مبسوطين منك اللي باسطانا😅
458193      BH       @Zzainabali @P_ameerah والله ماينده ابش يختي
458194      BH  @Al_mhbaa_7 شو عملنا لك حنا تهربي مننا احنا مس...
458195      BH        @haneenalmwla الله يبارك فيها وبالعافيه 😋😋😋
458196      BH          @jolnar121 السحله ضيفي ي بتطلع لك سحليه😅😅

[458197 rows x 2 columns]